/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

**/

#include <stdio.h>

//prototype
int fib (int n);

int main (void)
{
    int i = 0; int sum = 0;
    while (fib(i) < 4000000)
    {
        if( (fib(i) % 2) == 0)
            sum = sum + fib(i);
        i++;
    }
    
    printf("The answer is: %i \n", sum);
}

//recursion for fibonacci function
int fib (int n)
{
    if (n <= 1)
        return 1;
    else
        return fib(n-2) + fib(n-1);
}
